### ISSUE TITLE
CSRF Low Priority Question

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2#4]
Looking at PHP CSRF protection.

See there are methods in Laravel. Any lower-level mitigations for beginners?

**Comment by susanBuck** [comment]
It's not something we look at in this course, because we don't cover users/authentication, which is where CSRF becomes a risk. 

It is something I cover in [CSCI E-15](https://hesweb.dev/e15) (a good next step to this course).

For anyone reading this post and curious, CSRF stands for _Cross Site Request Forgery_, and it's a security issue where hackers will attempt to submit form data from their site to a victim site (e.g. cross-site). This is done with the intention of performing some action on a user's behalf using their logged in status on the victim site.

One way to battle CSRF is to build forms with a unique session identifier - think of it as a key to unlock a door. When the form is submitted, our server should check for that key. If it finds it, it means it's a valid request coming from our site. If the key is missing, it means it's potentially a fraudulent request coming from a different site, and the request should be rejected.

When using the Laravel framework (the real-world PHP framework on which our minimal e2framework is modeled after), CSRF protection is baked into your POST form requests. 

That being said, here's a straightforward CSRF implementation you can experiment with:

In your form, add a hidden field that stores a session id:

```html
<input type='hidden' name='csrf_token' value='{{ session_id() }}'>
```

Then, in the method that processes that form, confirm that session id exists:

```php
if ($this->app->input('csrf_token') != session_id()) {
    die('Request rejected');
}
```
